version: '3'

services:
  web: &web
    tty: true
    stdin_open: true
    build: .
    shm_size: '256mb'
    command: '--auto-servernum --server-num=1 ruby server.rb'
    volumes:
      - .:/app
    ports:
      - 9494:9494
  test:
    <<: *web
    command: '--auto-servernum --server-num=1 bundle exec rspec'