version: '3'

services:
  web: &web
    build: .
    shm_size: '256mb'
    command: sh -c 'bundle install && ruby server.rb'
    volumes:
      - .:/app
    ports:
      - 9494:9494
  test:
    <<: *web
    command: sh -c 'bundle exec rspec'